version: "3.8"

services:
  postgres:
    image: postgres:13
    container_name: jobber_postgres
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - jobber_network

  redis:
    image: redis:7-alpine
    container_name: jobber_redis
    ports:
      - "${REDIS_PORT}:6379"
    volumes:
      - redis_data:/data
    networks:
      - jobber_network

  flask_app:
    build: .
    container_name: jobber_flask_app
    ports:
      - "5000:5000"
    environment:
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=5432
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - Remodel_ID=${Remodel_ID}
      - Remodel_SECRET=${Remodel_SECRET}
    depends_on:
      - postgres
      - redis
    networks:
      - jobber_network
    volumes:
      - .:/app

volumes:
  postgres_data:
  redis_data:

networks:
  jobber_network:
    driver: bridge
