version: "3.8"
services:
  db:
    image: postgres:15
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: leads_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d leads_db"]
      interval: 5s
      timeout: 5s
      retries: 5

  app:
    build: .
    depends_on:
      db:
        condition: service_healthy
    environment:
      FLASK_ENV: development
      FLASK_DEBUG: 1
      FLASK_HOST: 0.0.0.0
      FLASK_PORT: 8080
      DB_USER: postgres
      DB_PASSWORD: postgres
      DB_HOST: db
      DB_NAME: leads_db
      DB_PORT: 5432
    ports:
      - "8080:8080"
    volumes:
      - .:/app

volumes:
  pgdata:
