exclude: "^tests/.*$"

repos:
  - repo: https://github.com/PyCQA/isort
    rev: 5.11.5
    hooks:
      - id: isort
        args: ["--sl", -l 100, "--profile", "black"]
        name: python - isort
        files: '\.py$'
  - repo: https://github.com/python/black
    rev: 22.3.0
    hooks:
      - id: black
        args: [-l 100]
        name: python - black
        files: '\.py$'
