#version: "3.8"

services:
  # flaskapi App Service
  app:
    build: 
        context: .
    container_name: zohocrm
    volumes:
      - ./src:/app/src
    depends_on:
      - postgres
      - redis
    ports:
      - "5000:5000" #connect port 5000 of local host to 5000 of docker
    networks:
      - zohocrm_network
    command: ["bash", "/app/entrypoint.sh"]


  # PostgreSQL Service
  postgres:
    image: postgres:17.4
    container_name: zohocrm_postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - zohocrm_network
    ports:
      - "5432:5432"

  
  # Redis Service
  redis:
    image: redis:7.4
    container_name: zohocrm_redis
    networks:
      - zohocrm_network



networks:
  zohocrm_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local

