version: "3.8"

services:
  # flaskapi App Service
  app:
    build:
      context: .
    container_name: zohocrm
    volumes:
      - ./src:/app/src
    depends_on:
      - postgres
      - redis
    ports:
      - "5000:5000" #connect port 5000 of local host to 5000 of docker
    networks:
      - zohocrm_network
    environment:
      - ZOHO_CLIENT_ID=${ZOHO_CLIENT_ID}
      - ZOHO_CLIENT_SECRET=${ZOHO_CLIENT_SECRET}
      - DATABASE_NAME=${DATABASE_NAME}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - CONNECTION_NAME=${CONNECTION_NAME}
      - CACHE_REDIS_HOST=${CACHE_REDIS_HOST}
      - CACHE_REDIS_PORT=${CACHE_REDIS_PORT}
      - CACHE_REDIS_PASSWORD=${CACHE_REDIS_PASSWORD}
      - CACHE_REDIS_USERNAME=${CACHE_REDIS_USERNAME}
      - GUNICORN_WORKERS=${GUNICORN_WORKERS}
      - GUNICORN_BIND=${GUNICORN_BIND}
      - GUNICORN_WORKER_CLASS=${GUNICORN_WORKER_CLASS}
    command: ["bash", "/app/entrypoint.sh"]

  # PostgreSQL Service
  postgres:
    image: postgres:17.4
    container_name: zohocrm_postgres
    environment:
      - POSTGRES_DB=${DATABASE_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - zohocrm_network
    ports:
      - "5432:5432"
  # Redis Service
  redis:
    image: redis:7.4
    container_name: zohocrm_redis
    networks:
      - zohocrm_network

networks:
  zohocrm_network:
    driver: bridge

volumes:
  postgres_data:
    driver: local
