version: "3.8"

services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
  redis:
    image: redis:7-alpine
    restart: always
    ports:
      - "6379:6379"

  web:
    build:
      context: .
      target: production
    env_file:
      - .prod.env
    ports:
      - "5050:5050"
    depends_on:
      - db
      - redis
    volumes:
      - .:/app
    restart: unless-stopped

volumes:
  postgres_data: 